/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  env: {
    USER_ACCOUNTS: process.env.USER_ACCOUNTS,
    NEXT_PUBLIC_DIALOGFLOW_PROJECT_ID: process.env.NEXT_PUBLIC_DIALOGFLOW_PROJECT_ID,
    NEXT_PUBLIC_DIALOGFLOW_AGENT_ID: process.env.NEXT_PUBLIC_DIALOGFLOW_AGENT_ID,
    NEXT_PUBLIC_DIALOGFLOW_LANGUAGE_CODE: process.env.NEXT_PUBLIC_DIALOGFLOW_LANGUAGE_CODE,
    NEXT_PUBLIC_DIALOGFLOW_LOCATION: process.env.NEXT_PUBLIC_DIALOGFLOW_LOCATION,
    NEXT_PUBLIC_DIALOGFLOW_CHAT_TITLE: process.env.NEXT_PUBLIC_DIALOGFLOW_CHAT_TITLE,
    NEXT_PUBLIC_DIALOGFLOW_CHAT_SUBTITLE: process.env.NEXT_PUBLIC_DIALOGFLOW_CHAT_SUBTITLE,
  },
}

module.exports = nextConfig